### PR TITLE
Re-render with conda-smithy 1.3.3

### PR DESCRIPTION
**Pull request by jjhelmus**
Increment build number and re-reder with conda-smithy 1.3.3

### CODE REVIEW

**Comment by jjhelmus** [comment]
Restarting AppVeyor build do to HTTP error.

**Comment by jakirkham** [comment]
Upstream is working on this issue ( https://github.com/Anaconda-Platform/support/issues/78 ).

**Comment by bgruening** [comment]
Can we restart this build. I'm in the need for a OSX version.
Thanks.

**Comment by ocefpaf** [comment]
Done in #17

**Pull request closed without merging**
