### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Can someone restart the AppVeyor build on this PR I seems to be broken.

**Comment by ocefpaf** [comment]
Oops too late :wink:

**Comment by jjhelmus** [comment]
Is AppVeyor really backed up or has this build stalled?

**Comment by ocefpaf** [comment]
I see 8 processes in the queue :unamused:

**Comment by jjhelmus** [comment]
Thanks fine, I'll be patient.

**Comment by ocefpaf** [comment]
I reversed #1 with this one. So now it is 7 :grin:

**Comment by jjhelmus** [comment]
This looks good to me, should fix the Windows build issue.  May want to revisit how the `vc` features are specified at a later time.

**Pull request merged**
