### PR TITLE
WIP: Upgrade to GLPK 4.60 and build shared library on Windows

### LINKED ISSUE #12: Shared library glpk.dll not installed for Windows
The Windows builds don't include the shared library `glpk.dll`. The equivalent files are included on Linux (`libglpk.so`) and macOS (`libglpk.dylib`). Is this just an oversight?

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This PR includes two changes:

- Upgrade from GLPK 4.59 to 4.60.
- Build and install shared library (`glpk.dll`) on Windows.

Closes #12.

In order to install the shared library I've had to include the version number in `bld.bat`. This isn't ideal, as it will break in future versions. Maybe this can be done with a wildcard? Submitting the PR now to trigger the build and test.

Also note that the shared libraries aren't currently tested explicitly. On Windows, the cython code will link against the static library. On OS X I don't think you can build shared libraries (?) so it's using the shared library. Not sure which it uses on Linux.

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
The package version is available in the `%PKG_VERSION%` environment variable, but the format is "4.60" not "4_60" so I'm not sure how to make use of this.

**Comment by jakirkham** [comment]
[This]( https://github.com/conda-forge/boost-feedstock/blob/35cc8f5991d543de154adf4e1ea96ea91ef36017/recipe/bld.bat#L35-L37 ) might help.

**Comment by snorfalorpagus** [comment]
Thanks @jakirkham. That was just what was needed.

**Comment by jakirkham** [comment]
Maybe we should add some tests for the Windows library?

Also this is an old recipe (so the issue proceeds this PR), but it could benefit from some file tests on all platforms.

**Comment by snorfalorpagus** [comment]
If you could point me in the direction of a newer recipe I don't mind doing the work to update it. GLPK is a core dependency in my project so I'm keen to get it working.

I could add a test using ctypes to test the shared library on Windows/Linux/Mac. Mac doesn't use static libraries, so that only needs testing on Windows/Linux. Presumably the extension could be configured to force a static link.

**Comment by snorfalorpagus** [comment]
I'm not sure what's causing the failure on circleci - it seems to be related to the conda-forge infrastructure rather than the recipe?

I've made the following changes:

- Upgraded to GLPK 4.60
- Check static and shared library file exists on Linux
- Check that shared library file exists on OS X (static is not built)
- Use ctypes to test shared library on all platforms
- Added myself to the maintainers list
- Added "description" item to recipe

I think the only thing that's missing from this is an explicit test of the static library on Linux and Windows. The Cython module *might* be doing this, but it's not explicit - I don't know how it decides which to use (static vs dynamic). Some platform-specific use of `extra_compile_args` could probably do this.

**Comment by aebrahim** [comment]
👍

**Comment by snorfalorpagus** [comment]
Huzzah! Green lights all over.

**Comment by jjhelmus** [comment]
LGTM, thanks for the update @snorfalorpagus!

**Comment by jakirkham** [comment]
Ooph, we forgot to re-render the feedstock. Could you please re-render with `conda-smithy` version `1.3.2` and do a build number bump, @jjhelmus ? Am worried we have OS X builds that don't have 10.9 compatibility here.

**Comment by jjhelmus** [comment]
@jakirkham Re-render done in PR #16

**Pull request merged**
