### PR TITLE
bump version to 4.63

### PR DESCRIPTION
**Pull request by dougalsutherland**

### CODE REVIEW

**Comment by dougalsutherland** [comment]
I don't know what's going on with the Travis failure. In the log, the `spam` extension seems to have built/linked/installed properly, but then it says `No module named 'spam'`. I also can't reproduce locally; it works on my 10.12 machine.

**Comment by snorfalorpagus** [comment]
@dougalsutherland I forced a rebuild on Travis and it seems to be OK now. I'm not sure what the issue was.

This change looks :+1: to me.

**Comment by jakirkham** [comment]
It looks good. We also need to [pin `gmp`]( https://github.com/conda-forge/conda-forge.github.io/blob/4bd1c85da242b04c2b24b0c0df2c49f7faa031b7/scripts/pin_the_slow_way.py#L50 ).

**Comment by jakirkham** [comment]
Thanks. LGTM.

**Comment by jakirkham** [comment]
Was noting some weird things that we were doing in the build including using Homebrew, which you pointed out here. Have tried to pull them into PR ( https://github.com/conda-forge/glpk-feedstock/pull/22 ). Given this version will break ABI, maybe we should make those changes first to the existing version first and then merge this. Thoughts?

**Comment by dougalsutherland** [comment]
Sounds good to me.

**Comment by dougalsutherland** [comment]
Rebased off of #22.

**Comment by jakirkham** [comment]
Sorry to ask this, but could we please rebase on `master`? That should clean up the diff a bit.

**Comment by dougalsutherland** [comment]
Yep, done.

**Comment by jakirkham** [comment]
LGTM. Thanks.

**Comment by jakirkham** [comment]
Do we care about 4.62 at all?

**Comment by dougalsutherland** [comment]
We can build 4.62 first if you want, it builds the same as .61 or .63 (this PR started that way). For what it matters, the ABI is [not compatible](https://abi-laboratory.pro/tracker/compat_report/glpk/4.62/4.63/439e6/abi_compat_report.html).

**Comment by jakirkham** [comment]
Right, but 4.61 and 4.62 are, correct? No strong feelings from me. Just figured this was the time to think about it.

**Comment by jakirkham** [comment]
Failure on AppVeyor is caused by re-rendering being out-of-date. Will submit a PR to the feedstock to fix this.

**Comment by jakirkham** [comment]
Toggling for CI.

**Comment by jakirkham** [comment]
Went ahead and made PR ( https://github.com/conda-forge/glpk-feedstock/pull/24 ) for 4.62 just for good measure in case it comes up. Sorry for all the delays on this one. 😞 Thanks for your patience.

**Comment by jakirkham** [comment]
Needs one more rebase and then should be good.

**Comment by dougalsutherland** [comment]
Somehow got this in a weird state where I'm having github trouble. Making a new PR.

**Comment by jakirkham** [comment]
Ok, no problem. Please let me know if I can help.

**Comment by jakirkham** [comment]
Replaced by PR ( https://github.com/conda-forge/glpk-feedstock/pull/26 ).

**Comment by dougalsutherland** [comment]
I think I screwed up my local clone by renaming remotes or something. It was weird, whatever. :)

**Pull request closed without merging**
