### PR TITLE
Re-rendered 2.1.1, Python 3.6, version 4.61

### PR DESCRIPTION
**Pull request by snorfalorpagus**
I need a Python 3.6 build for this, hence the rerender.

### CODE REVIEW

**Comment by jakirkham** [comment]
Strange that CI didn't start. Going to close and reopen.

**Comment by jakirkham** [comment]
Apparently GitHub is having some issues with webhooks, which is most likely causing this. Let's wait and see how it progresses.

**Comment by snorfalorpagus** [comment]
While I'm here I figured I'd upgrade the package version too.

**Comment by jakirkham** [comment]
SGTM. Updated the title to reflect that.

**Comment by snorfalorpagus** [comment]
@jakirkham I think this is ready now.

**Comment by jakirkham** [comment]
Thanks @snorfalorpagus.

**Pull request merged**
