### PR TITLE
Add run_exports

### PR DESCRIPTION
**Pull request by saraedum**
This package comes with some binaries but most likely when it is used in the host section it's because we link against it. Therefore I think a run_exports is warranted here.
See https://github.com/conda-forge/staged-recipes/pull/8951/files#r307970432.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Review by aebrahim — COMMENTED** [review]
I should probably be removed from the reviewers list

**Comment by saraedum** [comment]
This has happened in another PR in the meantime.

**Pull request closed without merging**
