### PR TITLE
Remove lint and re-render recipe

### LINKED ISSUE #6: MNT: The glpk recipe has some lint :(
This is the friendly conda-forge-admin automated user.

I've ran the conda-smithy linter and found some lint in this feedstock :cry:.

Here is what I have got:

  * Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form.

Thanks!

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #6

### CODE REVIEW

**Comment by jjhelmus** [comment]
@jakirkham This seems to fix the issue you were seeing in #8, do you want to include those changes in your PR or work from this one.

**Comment by pelson** [comment]
Excellent. LGTM 👍

**Comment by jakirkham** [comment]
Maybe we can @aebrahim if he remembers why `python` was missing from the build dependencies here.

**Comment by jjhelmus** [comment]
The feedstock was generated by conda-forge/staged-recipes#141 during which the Python dependency was moved from build to run in commit [73bc95](https://github.com/conda-forge/staged-recipes/pull/141/commits/73bc95b628fb471e3da0e4d1b43c8a338f0c193a).  Before that move the build was [failing in Python 3.5](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.222) but [worked with the change](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.232).  Looking at this now it seems as if the important part was to have python as a **run** dependency, not necessarily removing it as a build dependency. 

For the build itself python is not required but `conda smithy` requires it to render the matrix which is required in order the build for all three VC versions.

**Comment by aebrahim** [comment]
I think it was in there originally. Not sure why it was removed (I don't
think I even removed it).

**Comment by jakirkham** [comment]
Sounds like this sounds good to everyone. Going to go ahead and merge.

**Pull request merged**
