### PR TITLE
Retrigger CI

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by ocefpaf** [comment]
How does that look for you @jakirkham?

**Comment by jakirkham** [comment]
It's at least not dying immediately so better. Thanks @ocefpaf.

**Comment by jakirkham** [comment]
What did you do that fixed it?

**Comment by ocefpaf** [comment]
The queue is long and the new PRs to staged-recipes are taking precedence to the feedstocks.

> What did you do that fixed it?

Don't know what caused it, but all Appveyor build versions that started with `1.x` returned a message that the build already existed. So I bumped that number to `2.x`.

**Comment by jakirkham** [comment]
> The queue is long and the new PRs to staged-recipes are taking precedence to the feedstocks.

That's fine. Before it failed immediately regardless of how long the queue was so I think you fixed it.

> So I bumped that number to `2.x`.

Simple. Nice. I like it. This was just in the settings panel?

**Comment by jakirkham** [comment]
Honestly, this isn't changing anything. It was just a trick to get Windows to build and release. I think I will just merge it. So, that we spend time waiting to building not waiting to test an empty PR.

**Comment by ocefpaf** [comment]
> This was just in the settings panel?

Yep.

**Comment by jakirkham** [comment]
Cool. Thanks for clarifying. I'll keep my eyes open for this in the future.

**Comment by ocefpaf** [comment]
I will take a look to see what takes to give you access to AppVeyor.

**Comment by jakirkham** [comment]
Ok, thanks.

**Pull request merged**
